source 'https://rubygems.org'
# created by inline_forms 5.0.17

gem 'rails', '~> 5.1.4'
gem 'rake'
gem 'jquery-rails'
gem 'jquery-ui-sass-rails'
gem 'jquery-timepicker-rails'
gem 'capistrano'
gem 'will_paginate'
gem 'tabs_on_rails'
gem 'ckeditor'
gem 'cancan', :git => 'https://github.com/ortegacmanuel/cancan.git', :branch => '3.0'
gem 'carrierwave'
gem 'remotipart', '~> 1.0'
gem 'paper_trail'
gem 'devise'
gem 'inline_forms', git: 'https://github.com/ortegacmanuel/inline_forms.git', branch: 'bootstrap'
gem 'validation_hints'
gem 'mini_magick'
gem 'rails-i18n'
gem 'i18n-active_record', git: 'https://github.com/acesuares/i18n-active_record.git'
gem 'unicorn'
gem 'rvm'
gem 'rvm-capistrano', require: false
gem 'mysql2'
gem 'sass-rails'
gem 'coffee-rails'
gem 'therubyracer'
gem 'uglifier'
gem 'google-api-client'
gem 'dotenv-rails'
gem "bootstrap", ">= 4.1.2"
gem 'octicons_helper'
gem 'httparty'
gem 'bootstrap-glyphicons'

group :development do
  gem 'yaml_db'
  gem 'seed_dump', git: 'https://github.com/acesuares/seed_dump.git'
  gem 'switch_user'
  gem 'sqlite3'
  gem 'rspec-rails'
  gem 'shoulda'
  gem 'bundler'
  gem 'rspec'
  gem 'listen'
  gem 'byebug'
end
