source 'https://rubygems.org'
# created by inline_forms 5.0.17

gem 'rails', '~> 5.0.2'
gem 'rake'
gem 'jquery-rails'
gem 'jquery-ui-sass-rails'
gem 'capistrano'
gem 'will_paginate'
gem 'tabs_on_rails', git: 'https://github.com/acesuares/tabs_on_rails.git', branch: 'update_remote'
gem 'ckeditor'
gem 'cancan', git: 'https://github.com/acesuares/cancan.git', branch: '2.0'
gem 'carrierwave'
gem 'remotipart', '~> 1.0'
gem 'paper_trail'
gem 'devise'
gem 'inline_forms', '>=5'
gem 'validation_hints'
gem 'mini_magick'
gem 'rails-i18n'
gem 'i18n-active_record', git: 'https://github.com/acesuares/i18n-active_record.git'
gem 'unicorn'
gem 'rvm'
gem 'rvm-capistrano', require: false
gem 'foundation-rails', '~> 5.5'
gem 'mysql2'
gem 'sass-rails'
gem 'coffee-rails'
gem 'compass-rails'
gem 'foundation-icons-sass-rails'
gem 'therubyracer'
gem 'uglifier'
group :development do
  gem 'yaml_db'
  gem 'seed_dump', git: 'https://github.com/acesuares/seed_dump.git'
  gem 'switch_user'
  gem 'sqlite3'
  gem 'rspec-rails'
  gem 'shoulda'
  gem 'bundler'
  gem 'rspec'
  gem 'listen'
end
group :production do
  gem 'pg', '0.20.0'
end
