development:
  adapter: mysql2
  database: bankortografiko_dev
  username: root
  password: mersmaoc

production:
  adapter: mysql2
  database: bankortografiko_prod
  username: bankortografiko
  password: bankortografiko444
