development:
  adapter: mysql2
  database: bankortografiko_dev
  username: bankortografiko
  password: bankortografiko444

production:
  adapter: mysql2
  database: bankortografiko_prod
  username: bankortografiko
  password: bankortografiko444
